[build]
  functions = "functions/"
  command = "npm run build"
  publish = "dist/"

[template.environment]
  API_URL = "your Google Maps API endpoint"
  API_TOKEN = "your Google Maps API key"

[[redirects]]
from="/api"
to=".netlify/functions/getapi"
status=200
